add_newline = true

[directory]
read_only = ''
home_symbol = ' ~'
truncation_length = 4

[python]
symbol = " " 


[[battery.display]]
threshold = 25
style = 'bold red'
discharging_symbol = "󰁻 "
charging_symbol = "󰂆 "

[[battery.display]]
threshold = 45
style = 'bold yellow'
discharging_symbol = "󰁽 "
charging_symbol = "󰂈 "
