#!/usr/bin/bash

#swaylock -F -i "~/.config/hypr/wallpaper/MinimalismMountains.png"
swaylock \
--screenshots \
--indicator \
--font "JetBrainsMono Nerd Font" \
--clock \
--effect-vignette 0.7:1 \
--effect-blur 10x2

