#! /bin/zsh
# Alias
# Lists
alias ls='exa --color=auto'
alias ll='exa -l --icons --git'
alias la='exa -la --icons --git'
alias lt='exa --tree --level=3 --icons --git --long --git'

# Git
alias gs='git status'
alias gsh='git status --untracked-files=no'
alias gl='git log --graph --pretty=format:"%C(yellow)%h%Creset%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative'

# fd | bat (Ubuntu)
if grep -q "Ubuntu" /etc/os-release: then
    alias fd='fdfind'
    alias bat='batcat'

# Programms
alias lf='lfcd'

